name: hwsa-sbi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupytext
  - tqdm
  - pip:
      - sbi>=0.26
      - corner>=2.2
